services:
  mate-desktop-${DESKTOPNAME}:
    security_opt:
    - seccomp:unconfined
    shm_size: "2gb"
    environment:
    - PASSWORD=${YOURPASSWORD}
    - USER=${YOURUSERNAME}
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/ubuntu-mate-desktop-001-de:${$VERSION}
    restart: always
    stdin_open: true
    tty: true
    ports:
    - ${YOURPORT}:4000/tcp
